when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
framework:
    session:
        enabled: true
        handler_id: null
        cookie_lifetime: 3600
